### ISSUE TITLE
Mirror/import from gallery

### ISSUE THREAD

**Issue by Deer-Spangle** [mvdicarlo/postybirb-plus#170]
Hey there, not sure if this is within scope or postybirb, but I'm seeing a lot of folks who want to move their art gallery from one site to another (or to multiple others) lately, and wondering if this is something postybirb could support, or make easier?

I wonder whether you could just import posts and metadata json from a [gallery-dl](https://github.com/mikf/gallery-dl/) dump, for instance? That would save you from having to write scraping code

**Comment by askmeaboutlo0m** [comment]
I'm currently working on this, since I need it for my own purposes. It adds an "import directory" button on the Submissions/File page, which lets you pick a directory and then it tries to import stuff from there. At the time of writing, I have it importing a bunch of flat files from a directory, but I also want an importer for [the FurAffinity archiver thingy I wrote](https://github.com/askmeaboutlo0m/faescape) and one for exports from Mastodon. Extending these importers with one that understands a gallery-dl dump directory would then just be another exercise, probably not something I would implement myself though since I don't need it.

See [this branch over in the forked repo](https://github.com/askmeaboutlo0m/postybirb-plus/tree/import).

**Comment by mvdicarlo** [comment]
Assumed completed
